const types = {
  //
  GET_NOTES_START: 'GET_NOTES_START',
  GET_NOTES_SUCCESS: 'GET_NOTES_SUCCESS',
  GET_NOTES_ERROR: 'GET_NOTES_ERROR',
  //
  ADD_NOTE_START: 'ADD_NOTES_START',
  ADD_NOTE_SUCCESS: 'ADD_NOTES_SUCCESS',
  ADD_NOTE_ERROR: 'ADD_NOTES_ERROR',
  //
  DELETE_NOTE_START: 'DELETE_NOTES_START',
  DELETE_NOTE_SUCCESS: 'DELETE_NOTES_SUCCESS',
  DELETE_NOTE_ERROR: 'DELETE_NOTES_ERROR',
  //
  EDIT_NOTES_START: 'EDIT_NOTES_START',
  EDIT_NOTES_SUCCESS: 'EDIT_NOTES_SUCCESS',
  EDIT_NOTES_ERROR: 'EDIT_NOTES_ERROR',
  //
  GET_NOTES: 'GET_NOTES',
  ADD_NOTE: 'ADD_NOTE',
  DELETE_NOTE: 'DELETE_NOTE',
  EDIT_NOTE: 'EDIT_NOTE',
};

export default types;
